# Management cluster: mounting the docker socket is a hard requirement for CAPD.
# The CAPD controller runs inside the cluster and uses this socket to ask the host's Docker for "machine" containers
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
